const questions = [
    ["eat a snail", "pet a porcupine"],
    ["swim with a blind shark ", "swim with a box jelly fish"],
    ["get lost in a maze", "get lost in a busy road"],
    ["live in the desert", "live in the jungle"],
    ["eat poo", "drink pee"],
    ["have a pet dog", "have a pet cat"],
    ["drink coffee", "drink chocolate milk shake"],
    ["be 1 year old forever", "be 100 years old forever"],
    ["be able to see the future", "fly"],
    ["breath under water", "be able to live In the space forever without oxygen"],
    ["read 100 thick books", "1000 thin book"],
    ["Sleep with a vampire", "play with a zombie"],
    ["have a pet alligator", "wolf"],
    ["eat doughnut", "chocolate cake"],
    ["draw something worth $100000", "go on World record"],
    ["become famous", "be very talented"],
    ["read a cooking book", "a history book"],
    ["make slime", "become famous"],
    ["become famous", "live a peaceful life"],
    ["live in a castle", "in a mansion."],
    ["make friend with a giant", "have no friends."],
    ["get an A + in art", "get a b -  for English."],
    ["get famous", "live in a mansion"],
    ["get a iPhone 15", "win $10000"],
    ["catch a rare butterfly", "catch a bird"],
    ["eat a shark", "sleep with a shark"],
    ["swim with Mermaid", "fly with a Unicorn"],
    ["watch TV", "play video games"],
    ["play violin", "play piano"],
    ["have a best friend", "have a good ice cream"]
]

export default questions

